# Document Version: 1.0
# author @mvxt

#####################
# Common Definitions
#####################
common:
  - &project_dir "~/complete-software-roadmap"

orbs:
  aws-s3: circleci/aws-s3@1.0.3

############
# Workflows
############
workflows:
  version: 2.1
  deploy:
    jobs:
      - push-s3:
          context: static-void-prod
          filters:
            branches:
              only: master

##################
# Job Definitions
##################
version: 2.1
jobs:
  push-s3:
    docker:
      - image: circleci/python:2.7
    working_directory: *project_dir
    steps:
      - checkout
      - aws-s3/copy:
          from: "./sva-roadmap.svg"
          to: "s3://staticvoid.dev/software-roadmap/sva-roadmap.svg"

